React Calculator App Milestone 4
SajjadAhmad14/Calculator-App-React pull request #3
Opened 2021-06-02 14:41 UTC by SajjadAhmad14

- Added logic directory inside src.
- Added calculate.js and operate.js functions and their implementation.
- Fixed eslint errors.

2021-06-02 15:43 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @SajjadAhmad14, great job on this milestone :smile: The right linter files are used :muscle: The PR and README are descriptive :+1: Commit messages are easy to understand :1st_place_medal: However, there a few comments we need to address, kindly check the inline comments below:


Once these are addressed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-06-02 15:43 UTC, addod19 commented on src/logic/operate.js
> +      Big(numberOne - numberTwo);
Kindly use `minus` instead of `-`

2021-06-02 15:43 UTC, addod19 commented on src/logic/operate.js
> +      Big(numberOne + numberTwo);
Kindly use the `plus` method instead of `+`

2021-06-02 15:43 UTC, addod19 commented on src/logic/operate.js
> +      Big(numberOne * numberTwo);
Kindly use the `times` method instead of `*`

2021-06-02 15:43 UTC, addod19 commented on src/logic/operate.js
> +      Big(numberOne / numberTwo);
Kindly use the `div` method instead of `/`

2021-06-02 15:43 UTC, addod19 commented on src/logic/operate.js
> +      Big(numberOne % numberTwo);
Kindly use the `mod` method instead of `%` to convert a number into a percentage

2021-06-02 15:43 UTC, addod19 commented on src/logic/calculate.js
> +export default calculate;
The calculate function is not complete, kindly write a condition for all the remaining buttons; for example; `AC` to clear the input, `%` to turn a number into a percentage, and a default condition

2021-06-02 15:43 UTC, addod19 commented on src/logic/calculate.js
> +  let { total, next } = data;
The calculator data object contains three properties: total, next, operation. Let us kindly fix this

2021-06-03 07:54 UTC, SajjadAhmad14 commented on src/logic/operate.js
> +      Big(numberOne - numberTwo);
Thank you! Where does minus come from? Is it a built-in React or JavaScript method?

2021-06-03 08:53 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes.
Please add the `AC` button for clearing inputs.


### Martin Afani
#### Slack: whiz25

2021-06-03 08:53 UTC, afanimartin commented on src/logic/calculate.js
> +    case '+/-':
- Add `AC` button for clearing inputs

2021-06-03 09:17 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-06-03 09:21 UTC, merged